### ISSUE TITLE
ryan umbrella ticket-email subscription

### ISSUE THREAD

**Issue by ryanmgds** [noahahooja/p4schlimes#13]
Email Subscription for daily stock news. User inputs email, output is daily news about stocks. Finished and deployed.

- [x] user input for email
- [x] output of stock information
- [x] nice css on home page

Link to evidece- https://github.com/noahahooja/p4schlimes/blob/main/main.py#L30 (line28-38)

https://github.com/noahahooja/p4schlimes/blob/main/templates/main.html (line110-128)

**Comment by ryanmgds** [comment]
Email Subscription for daily stock news. User inputs email, output is daily news about stocks. Finished and deployed.

**Comment by noahahooja** [comment]
Ticket looks good, try to see if you can fit the email subscription part somewhere that fits better on the homepage rather then just under the main navbar.

**Comment by BraydenBasinger** [comment]
I like the ticket. I think that you could embed a website like the WSJ or CNN that has price updates for stocks daily. But so far its looking good.

**Comment by 1855495** [comment]
The ticket appears to be in good condition; however, see if you can place the email subscription section somewhere on the homepage that is more prominent than simply beneath the main navbar.

**Comment by lolabulkin** [comment]
Nice ticket Ryan. Organized and well fit for your project. Try and add more clearance on how email works, and maybe a better implementation into the website navigation wise 🤙🏼
