### ISSUE TITLE
noah umbrella ticket 6/1: CRUD Review Page for users

### ISSUE THREAD

**Issue by noahahooja** [noahahooja/p4schlimes#17]
I implemented CRUD as a review page for users to give advice about our project and enter some of the scores they have gotten through our stock simulator. 
Runtime link: http://76.167.172.90/ 
Link to code: https://github.com/noahahooja/p4schlimes/blob/main/templates/userreview.html
- [x] CRUD page is clean, fits border of screen
- [x] Different areas for users to enter on (2-3 different spots)
- [x] Has spot for email to work with Ryan's subscription ticket

**Comment by ryanmgds** [comment]
Very well rounded ticket. Good use of CRUD and nice idea for project. Maybe consider making it a bit cleaner with some CSS. good job

**Comment by BraydenBasinger** [comment]
I like the use of CRUD with your ticket. Like Noah said, you could incorporate some CSS and better styling. But I like how it is turning out so far.

**Comment by 1855495** [comment]
This is a very well-rounded ticket. Good usage of CRUD and a good project idea. Consider using CSS to make it a little cleaner. excellent work

**Comment by TMarwah** [comment]
CRUD looks to be well developed but maybe some CSS formatting could make it easier to navigate.

**Comment by carterquartararo** [comment]
Looks good way to use CRUD and implement it into the project
