### ISSUE TITLE
noah future ticket umbrella- visuals to about us pages, etc.

### ISSUE THREAD

**Issue by noahahooja** [noahahooja/p4schlimes#18]
For my future ticket, I want to add images and background colors to our pages such as the about us page so it is not just plain white text.

**Comment by noahahooja** [comment]
- [x] include college board ideas
- [x] describe what our website offers to users
- [x] tell purpose of site
link to code: https://github.com/noahahooja/p4schlimes/blob/main/templates/whatstocks.html 
link to runtime: http://76.167.172.90/

**Comment by carterquartararo** [comment]
Good idea to add to the theme of project!!

**Comment by colinktran** [comment]
Good ticket, although it need better organization and a more clear goal.

**Comment by BraydenBasinger** [comment]
I like the code. This fits in with our website theme very well

**Comment by ryanmgds** [comment]
Nice ticket Noah. Lacking code but is what our project needs. This is a good step as this project is coming to an end.
